# Generated by Django 5.2.3 on 2025-06-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='data',
            new_name='date',
        ),
    ]
